#!/bin/bash
echo "Windows 10 transformation script
Designed by Botspot
"

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR

echo "Installing $DIR/root"
sleep 1

if [ -d $DIR/backup/home ];then
  echo "WARNING! It appears there"\'"s already a backup at $DIR/backup. If you continue, it will be overwritten. Continue? [Y/n]"
  read answer
  if [ $answer == 'n' ];then
    echo "OK, exiting now."
    exit 0
  fi
fi

echo "Backing up config files"
mkdir -p $DIR/backup
cd $DIR/root
cp --parents -a $(find $HOME/.config -type f | sed -e 's#^#/#' | tr '\n' ' ' ) $DIR/backup  &>/dev/null
cd

echo "Copying the new files in"
sudo cp -a ${DIR}/root/. /

echo "Installing composite manager, GTK engine, and tint2"
echo ""
echo ""
sudo apt install xcompmgr tint2 gtk2-engines-murrine -y --no-install-recommends
echo ""
echo ""
echo "Installation complete. Refreshing desktop session now, but rebooting is recommended."
sudo update-icon-caches /usr/share/icons/*
sleep 1
openbox --restart &>/dev/null
killall tint2 pcmanfm lxpanel &>/dev/null
rm -r ~/.cache/tint2 &>/dev/null
sleep 5
tint2 &>/dev/null &
sleep 1
lxpanel --profile LXDE-pi &>/dev/null &
sleep 2

openbox --restart &>/dev/null
sleep 1
pcmanfm --desktop --profile LXDE-pi &>/dev/null &
sleep 2

xcompmgr -C -c -o 0.5 -l -19 -t -10 -r 14 -f -O 0.05 -I 0.05 &>/dev/null &
sleep 1

if [ -f /usr/bin/conky ];then
  echo 'restarting conky'
  killall conky
  sleep 1
  conky &>/dev/null &
  sleep 1
fi

zenity --info --text="Have a look around.\nPlease let me know if there is anything I can improve. \n\n -Botspot" --icon-name=emblem-default --ellipsize &>/dev/null &

sleep 5
exit 0

