#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR
echo "Uninstalling from $DIR"
echo ""
killall xcompmgr tint2
echo "Removing themes and window border"
sudo rm -r /usr/share/themes/Windows-10
sudo rm -r /usr/share/themes/Windows-10-2
echo "Removing icons and mouse pointer"
sudo rm -r /usr/share/icons/Windows-10
echo "Removing fonts"
sudo rm -r "/usr/share/fonts/truetype/Google Sans"
echo "Removing tint2 autostart"
sudo rm "~/.config/autostart/tint2.desktop"
echo "Removing config files"
cd $DIR/root
rm $(find home/pi/.config -type f | sed -e 's#^#/#' | tr '\n' ' ' ) $DIR/backup &>/dev/null
cd
echo "Restoring original config files"
sudo cp -a $DIR/backup/. /
echo "Removing composite manager and GTK engine"

#echo ""
#echo ""
#sudo apt purge xcompmgr gtk2-engines-murrine tint2 -y
#echo ""
#echo ""
echo "Uninstallation complete. Refreshing desktop."
killall pcmanfm lxpanel
sleep 5
lxpanel --profile LXDE-pi &
sleep 3
openbox --restart
pcmanfm --desktop --profile LXDE-pi &>/dev/null &
