#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $DIR
echo "Uninstalling from $DIR"
echo ""
killall xcompmgr tint2
echo "Removing themes and window border"
sudo rm -rf /usr/share/themes/Windows-10
sudo rm -rf /usr/share/themes/Windows-10-2
echo "Removing icons and mouse pointer"
sudo rm -rf /usr/share/icons/Windows-10
echo "Removing fonts"
sudo rm -rf "/usr/share/fonts/Google Sans"
echo "Removing config files"
cd $DIR/root
rm $(find home/pi/.config -type f | sed -e 's#^#/#' | tr '\n' ' ' ) $DIR/backup &>/dev/null
cd
echo "Restoring original config files"
sudo cp -a $DIR/backup/. /
echo "Removing composite manager and GTK engine"

#echo ""
#echo ""
#sudo apt purge xcompmgr gtk2-engines-murrine tint2 -y
#echo ""
#echo ""
echo "Uninstallation complete. Refreshing desktop."
killall pcmanfm lxpanel &>/dev/null
sleep 5
lxpanel --profile LXDE-pi &>/dev/null &
sleep 3

openbox --restart &>/dev/null
pcmanfm --desktop --profile LXDE-pi &>/dev/null &
openbox --restart &>/dev/null

if [ -f /usr/bin/conky ];then
  killall conky
  sleep 1
  conky &>/dev/null &
  sleep 1
fi

echo "removing backup"
gio trash $DIR/backup
